//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FusionLOS.MortgegeOrigination {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LosCustomerImportDto", Namespace="http://schemas.datacontract.org/2004/07/Mortgagebot.LOS")]
    [System.SerializableAttribute()]
    public partial class LosCustomerImportDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AccountIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid CustomerGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AccountId {
            get {
                return this.AccountIdField;
            }
            set {
                if ((this.AccountIdField.Equals(value) != true)) {
                    this.AccountIdField = value;
                    this.RaisePropertyChanged("AccountId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid CustomerGuid {
            get {
                return this.CustomerGuidField;
            }
            set {
                if ((this.CustomerGuidField.Equals(value) != true)) {
                    this.CustomerGuidField = value;
                    this.RaisePropertyChanged("CustomerGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uri {
            get {
                return this.UriField;
            }
            set {
                if ((object.ReferenceEquals(this.UriField, value) != true)) {
                    this.UriField = value;
                    this.RaisePropertyChanged("Uri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlData {
            get {
                return this.XmlDataField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlDataField, value) != true)) {
                    this.XmlDataField = value;
                    this.RaisePropertyChanged("XmlData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LosCustomerImportStatus", Namespace="http://schemas.datacontract.org/2004/07/Mortgagebot.LOS")]
    public enum LosCustomerImportStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IpAddressNotConfigured = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartnerIdNotConfiguredForLosUrl = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoLosSiteFound = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Timeout = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PosFailedToWriteMoFile = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mortgagebot.com", ConfigurationName="MortgegeOrigination.IMortgagebotOriginationImport")]
    public interface IMortgagebotOriginationImport {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mortgagebot.com/IMortgagebotOriginationImport/ImportMortgageOriginatio" +
            "nData", ReplyAction="http://www.mortgagebot.com/IMortgagebotOriginationImport/ImportMortgageOriginatio" +
            "nDataResponse")]
        FusionLOS.MortgegeOrigination.LosCustomerImportStatus ImportMortgageOriginationData(FusionLOS.MortgegeOrigination.LosCustomerImportDto customerInformation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mortgagebot.com/IMortgagebotOriginationImport/ImportMortgageOriginatio" +
            "nData", ReplyAction="http://www.mortgagebot.com/IMortgagebotOriginationImport/ImportMortgageOriginatio" +
            "nDataResponse")]
        System.Threading.Tasks.Task<FusionLOS.MortgegeOrigination.LosCustomerImportStatus> ImportMortgageOriginationDataAsync(FusionLOS.MortgegeOrigination.LosCustomerImportDto customerInformation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMortgagebotOriginationImportChannel : FusionLOS.MortgegeOrigination.IMortgagebotOriginationImport, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MortgagebotOriginationImportClient : System.ServiceModel.ClientBase<FusionLOS.MortgegeOrigination.IMortgagebotOriginationImport>, FusionLOS.MortgegeOrigination.IMortgagebotOriginationImport {
        
        public MortgagebotOriginationImportClient() {
        }
        
        public MortgagebotOriginationImportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MortgagebotOriginationImportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MortgagebotOriginationImportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MortgagebotOriginationImportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FusionLOS.MortgegeOrigination.LosCustomerImportStatus ImportMortgageOriginationData(FusionLOS.MortgegeOrigination.LosCustomerImportDto customerInformation) {
            return base.Channel.ImportMortgageOriginationData(customerInformation);
        }
        
        public System.Threading.Tasks.Task<FusionLOS.MortgegeOrigination.LosCustomerImportStatus> ImportMortgageOriginationDataAsync(FusionLOS.MortgegeOrigination.LosCustomerImportDto customerInformation) {
            return base.Channel.ImportMortgageOriginationDataAsync(customerInformation);
        }
    }
}
